#
# Copyright 2017 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-streaming-queue
  namespace: <Name of cspace> # example - externalcspace
spec:
  sparkConf:
    spark.mapr.cluster.configMap: mapr-cluster-cm
    spark.mapr.user.secret: <Name of users secret> # example - mapr-user-secret-123456
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "maprfs:///apps/spark/<Name of cspace>" # example - maprfs:///apps/spark/externalcspace
  type: Scala
  sparkVersion: 2.4.4
  mode: cluster
  image: gcr.io/mapr-hpe/spark-2.4.4:201912102008
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.streaming.QueueStream
  mainApplicationFile: "local:///opt/mapr/spark/spark-2.4.4/examples/jars/spark-examples_2.11-2.4.4.0-mapr-630.jar"
  restartPolicy:
    type: Never
  imagePullSecrets:
  - mapr-imagepull-secrets
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 2.4.4
    serviceAccount: <Name of cspace service account> # example - mapr-externalcspace-cspace-sa
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.4
