apiVersion: mke.hpe.com/v1
kind: DrillCluster
metadata:
  name: drillcluster1
spec:
  cspace: mycspace
  imageregistry: gcr.io/mapr-hpe
  image: drill-1.16.0:latest
  count: 2
  maxcount: 4
  disablesecurity: false
  memory: 4Gi
  cpu: 4000m
  cputhreshold: 75
  httpport: 8047
  userport: 21010
  podtimeout: 60
  loglevel: DEBUG
